# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from ocr_pypi.proto import ocr_pb2 as ocr__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ocr_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OCRServiceStub(object):
    """---------------------------------------------------------------------------
    Service definition
    ---------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessDocument = channel.unary_stream(
                '/ocr.OCRService/ProcessDocument',
                request_serializer=ocr__pb2.ProcessDocumentRequest.SerializeToString,
                response_deserializer=ocr__pb2.ProcessDocumentResponse.FromString,
                _registered_method=True)
        self.ListProviders = channel.unary_unary(
                '/ocr.OCRService/ListProviders',
                request_serializer=ocr__pb2.ListProvidersRequest.SerializeToString,
                response_deserializer=ocr__pb2.ListProvidersResponse.FromString,
                _registered_method=True)
        self.ListTemplates = channel.unary_unary(
                '/ocr.OCRService/ListTemplates',
                request_serializer=ocr__pb2.ListTemplatesRequest.SerializeToString,
                response_deserializer=ocr__pb2.ListTemplatesResponse.FromString,
                _registered_method=True)
        self.ValidateDocument = channel.unary_unary(
                '/ocr.OCRService/ValidateDocument',
                request_serializer=ocr__pb2.ValidateDocumentRequest.SerializeToString,
                response_deserializer=ocr__pb2.ValidateDocumentResponse.FromString,
                _registered_method=True)
        self.ValidateTemplate = channel.unary_unary(
                '/ocr.OCRService/ValidateTemplate',
                request_serializer=ocr__pb2.ValidateTemplateRequest.SerializeToString,
                response_deserializer=ocr__pb2.ValidateTemplateResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/ocr.OCRService/HealthCheck',
                request_serializer=ocr__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=ocr__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class OCRServiceServicer(object):
    """---------------------------------------------------------------------------
    Service definition
    ---------------------------------------------------------------------------

    """

    def ProcessDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProviders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTemplates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateTemplate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OCRServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessDocument': grpc.unary_stream_rpc_method_handler(
                    servicer.ProcessDocument,
                    request_deserializer=ocr__pb2.ProcessDocumentRequest.FromString,
                    response_serializer=ocr__pb2.ProcessDocumentResponse.SerializeToString,
            ),
            'ListProviders': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProviders,
                    request_deserializer=ocr__pb2.ListProvidersRequest.FromString,
                    response_serializer=ocr__pb2.ListProvidersResponse.SerializeToString,
            ),
            'ListTemplates': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTemplates,
                    request_deserializer=ocr__pb2.ListTemplatesRequest.FromString,
                    response_serializer=ocr__pb2.ListTemplatesResponse.SerializeToString,
            ),
            'ValidateDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateDocument,
                    request_deserializer=ocr__pb2.ValidateDocumentRequest.FromString,
                    response_serializer=ocr__pb2.ValidateDocumentResponse.SerializeToString,
            ),
            'ValidateTemplate': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateTemplate,
                    request_deserializer=ocr__pb2.ValidateTemplateRequest.FromString,
                    response_serializer=ocr__pb2.ValidateTemplateResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=ocr__pb2.HealthCheckRequest.FromString,
                    response_serializer=ocr__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ocr.OCRService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ocr.OCRService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OCRService(object):
    """---------------------------------------------------------------------------
    Service definition
    ---------------------------------------------------------------------------

    """

    @staticmethod
    def ProcessDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ocr.OCRService/ProcessDocument',
            ocr__pb2.ProcessDocumentRequest.SerializeToString,
            ocr__pb2.ProcessDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProviders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ocr.OCRService/ListProviders',
            ocr__pb2.ListProvidersRequest.SerializeToString,
            ocr__pb2.ListProvidersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTemplates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ocr.OCRService/ListTemplates',
            ocr__pb2.ListTemplatesRequest.SerializeToString,
            ocr__pb2.ListTemplatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ocr.OCRService/ValidateDocument',
            ocr__pb2.ValidateDocumentRequest.SerializeToString,
            ocr__pb2.ValidateDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateTemplate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ocr.OCRService/ValidateTemplate',
            ocr__pb2.ValidateTemplateRequest.SerializeToString,
            ocr__pb2.ValidateTemplateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ocr.OCRService/HealthCheck',
            ocr__pb2.HealthCheckRequest.SerializeToString,
            ocr__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
