# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: types.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'types.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btypes.proto\x12\x03ocr*G\n\tOCRStatus\x12\x0f\n\x0bIDLE_STATUS\x10\x00\x12\x0e\n\nPROCESSING\x10\x01\x12\r\n\tCOMPLETED\x10\x02\x12\n\n\x06\x46\x41ILED\x10\x03*a\n\x08OCRStage\x12\x08\n\x04IDLE\x10\x00\x12\x0e\n\nVALIDATING\x10\x01\x12\x0f\n\x0b\x44OWNLOADING\x10\x02\x12\x0e\n\nEXTRACTING\x10\x03\x12\x0c\n\x08\x43HUNKING\x10\x04\x12\x0c\n\x08\x46INISHED\x10\x05*:\n\x0cHealthStatus\x12\x16\n\x12HEALTH_NOT_SERVING\x10\x00\x12\x12\n\x0eHEALTH_SERVING\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OCRSTATUS']._serialized_start=20
  _globals['_OCRSTATUS']._serialized_end=91
  _globals['_OCRSTAGE']._serialized_start=93
  _globals['_OCRSTAGE']._serialized_end=190
  _globals['_HEALTHSTATUS']._serialized_start=192
  _globals['_HEALTHSTATUS']._serialized_end=250
# @@protoc_insertion_point(module_scope)
